import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "src/components/Button";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Oi mundo!</a>
        </h1>

        <Button />
      </main>
    </div>
  );
};

export default Home;
